language: php
php:
- '5.6'

script: echo "We don't have tests yet :("

before_deploy:
- sh package.sh

deploy:
  provider: releases
  name: "$TRAVIS_TAG"
  api_key:
    secure: MSGWPC+wc6apv9jw5JkN5FPYbg/KTC2vA7WtAXDAqR3/B44yqmoUVY7UWJQiQq4EwzIvOSsfJxPwkXS7ejz/RnXuTdfGglYxja+EjEWhdlNWQFscVoepMHx68Za8o0xciOxNV+6HhS3EQp2egmCw1ET1qSHLi3kQZXENcna/UbgSiYzMGc6sJCibdKRtC93pNbOwHUq3ldyJdq0k+W8xn+1jE/IBvPbdOzlqY03pU6ZBNOHd6LYFN2+K8t60H9U+8PTbaf0dVZK3DwZ5KLhH/5EFcUGWewNC6KZn2fsYFQqiJVHa6teKJc1jiA6/pGFgmiwO0Moxk+D5a3iy6OD2IKCR6W6uTqsrgG0D1/pZz3g0VEhZzhGRR96///BWDaqk+TmX1BoRCS0P8qx+VJCbJCDjj7QPghpfFhyJcWHzco9FR6cLOmilJ3EyGvjHrg1TN9SPjpnlaq4TchOobbSFgEHFA1uU24S7MtKH1ktSm5h7MssvXbPLiJtH0NybBg7SKJUaZjU0eX6Eo6XyZhFf0tJFWg6jwCQ44ZESpPwEGw2uCxjipGwPUj5JuUbXcmM5f3jWHtYDWdInituHNhg9eQ7oJsm/lUQ8myjMDUPiHqBenpc7py7xIroFUOQd+9xnWeXFxL/BEi9r5tqaJWUVK3/0SePNlNfpUZm6++RT41o=
  file: "plugin-prestashop-webpay-$TRAVIS_TAG.zip"
  skip_cleanup: true
  on:
    repo: TransbankDevelopers/transbank-plugin-prestashop-webpay
    tags: true
